version: "3.4"

services:
    devdb:
        image: postgres:alpine
        restart: always
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_PASSWORD=pass
            - POSTGRES_USER=usr
            - POSTGRES_DB=tm_db_dev
    testdb:
        image: postgres:alpine
        restart: always
        ports:
        - "5434:5432"
        environment:
        - POSTGRES_PASSWORD=pass
        - POSTGRES_USER=usr
        - POSTGRES_DB=tm_db_test


